from django.urls import path
from . import views


urlpatterns = [
	path('', views.login, name='login'),
	path('home/', views.index, name='index'),
	path('payment/', views.payment, name='payment'),
	path('card_pm/', views.card_pm, name='card_pm'),
	path('card_pm_ol/', views.card_pm_ol, name='card_pm_ol'),
	path('vir_acc/', views.vir_acc, name='vir_acc'),
	path('acc_tran/', views.acc_tran, name='acc_tran'),
	path('ceph_pm/', views.ceph_pm, name='ceph_pm'),
	path('cash_pm/', views.cash_pm, name='cash_pm'),
	path('cash_pm_ol/', views.cash_pm_ol, name='cash_pm_ol'),
	path('card_plm_ip/', views.card_plm_ip, name='card_plm_ip'),
	path('card_plm/', views.card_plm, name='card_plm'),
	path('refund/', views.refund, name='refund'),
	path('purchase_case/', views.purchase_case, name='purchase_case'),
	path('purchase_li/', views.purchase_li, name='purchase_li'),
	path('purchase_li_file/', views.purchase_li_file, name='purchase_li_file'),
	path('purchase_li_rs/', views.purchase_li_rs, name='purchase_li_rs'),
	path('sch_cal/', views.sch_cal, name='sch_cal'),
	path('pmdate_li/', views.pmdate_li, name='pmdate_li'),
	path('pmmethod_li/', views.pmmethod_li, name='pmmethod_li'),
	path('outsam_li/', views.outsam_li, name='outsam_li'),
	path('balance_li/', views.balance_li, name='balance_li'),
	path('pmpostpone_li/', views.pmpostpone_li, name='pmpostpone_li'),
	path('taxinvoice_li/', views.taxinvoice_li, name='taxinvoice_li'),
	path('cardtt_rp/', views.cardtt_rp, name='cardtt_rp'),
	path('acctrantt_rp/', views.acctrantt_rp, name='acctrantt_rp'),
	path('viracctt_rp/', views.viracctt_rp, name='viracctt_rp'),
	path('cephpm_rp/', views.cephpm_rp, name='cephpm_rp'),
	path('cashpm_rp/', views.cashpm_rp, name='cashpm_rp'),
	path('card_charge/', views.card_charge, name='card_charge'),
	path('test/', views.test, name='test'),
    # path('', views.post_list, name='post_list'),
    # path('post/<int:pk>/', views.post_detail, name='post_detail'),
    # path('post/new', views.post_new, name='post_new'),
    # path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]